# Generated by Django 4.0.1 on 2022-01-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_tag_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='is_active',
        ),
    ]
